// AWS EC2-specific extensions for the asset model

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: awsec2_model.proto

package resources

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Ec2VM struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InstanceType string `protobuf:"bytes,1,opt,name=instance_type,json=instanceType,proto3" json:"instance_type,omitempty"` // The full instance type, such as "t3.medium"
	Region       string `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"`                                 // The Aws Region, for a regional instance
	Zone         string `protobuf:"bytes,3,opt,name=zone,proto3" json:"zone,omitempty"`                                     // Wavelength Zone or local Zone, for a zonal instance
	// TODO: maybe combine term_type, purchase_option, offering_class, and tenancy
	// into one proto?
	TermType       string `protobuf:"bytes,4,opt,name=term_type,json=termType,proto3" json:"term_type,omitempty"`                   // OnDemand or Reserved
	PurchaseOption string `protobuf:"bytes,5,opt,name=purchase_option,json=purchaseOption,proto3" json:"purchase_option,omitempty"` // only for TermType=Reserved: "No Upfront", "Partial Upfront" or "All Upfront"
	OfferingClass  string `protobuf:"bytes,6,opt,name=offering_class,json=offeringClass,proto3" json:"offering_class,omitempty"`    // Only for TermType=Reserved: "convertible" or "standard"
	Tenancy        string `protobuf:"bytes,7,opt,name=tenancy,proto3" json:"tenancy,omitempty"`                                     // Dedicated, Shared, Host, NA, Reserved
	Os             string `protobuf:"bytes,8,opt,name=os,proto3" json:"os,omitempty"`                                               // Linux, SUSE, Windows, RHEL, NA.
	// No License required, Bring your own license, NA -- not sure if relevant here.
	LicenseModel string `protobuf:"bytes,9,opt,name=license_model,json=licenseModel,proto3" json:"license_model,omitempty"`
}

func (x *Ec2VM) Reset() {
	*x = Ec2VM{}
	if protoimpl.UnsafeEnabled {
		mi := &file_awsec2_model_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ec2VM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ec2VM) ProtoMessage() {}

func (x *Ec2VM) ProtoReflect() protoreflect.Message {
	mi := &file_awsec2_model_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ec2VM.ProtoReflect.Descriptor instead.
func (*Ec2VM) Descriptor() ([]byte, []int) {
	return file_awsec2_model_proto_rawDescGZIP(), []int{0}
}

func (x *Ec2VM) GetInstanceType() string {
	if x != nil {
		return x.InstanceType
	}
	return ""
}

func (x *Ec2VM) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Ec2VM) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *Ec2VM) GetTermType() string {
	if x != nil {
		return x.TermType
	}
	return ""
}

func (x *Ec2VM) GetPurchaseOption() string {
	if x != nil {
		return x.PurchaseOption
	}
	return ""
}

func (x *Ec2VM) GetOfferingClass() string {
	if x != nil {
		return x.OfferingClass
	}
	return ""
}

func (x *Ec2VM) GetTenancy() string {
	if x != nil {
		return x.Tenancy
	}
	return ""
}

func (x *Ec2VM) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Ec2VM) GetLicenseModel() string {
	if x != nil {
		return x.LicenseModel
	}
	return ""
}

type Ec2Disk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VolumeType string `protobuf:"bytes,1,opt,name=volume_type,json=volumeType,proto3" json:"volume_type,omitempty"` // General Purpose, Throughput Optimized HDD, Cold HDD.
	// The volume type has a maximum size, this is the actual size. Note the minimal
	// size tends to be something like 1GiB.
	ActualSizeGb uint64 `protobuf:"varint,2,opt,name=actual_size_gb,json=actualSizeGb,proto3" json:"actual_size_gb,omitempty"`
}

func (x *Ec2Disk) Reset() {
	*x = Ec2Disk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_awsec2_model_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ec2Disk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ec2Disk) ProtoMessage() {}

func (x *Ec2Disk) ProtoReflect() protoreflect.Message {
	mi := &file_awsec2_model_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ec2Disk.ProtoReflect.Descriptor instead.
func (*Ec2Disk) Descriptor() ([]byte, []int) {
	return file_awsec2_model_proto_rawDescGZIP(), []int{1}
}

func (x *Ec2Disk) GetVolumeType() string {
	if x != nil {
		return x.VolumeType
	}
	return ""
}

func (x *Ec2Disk) GetActualSizeGb() uint64 {
	if x != nil {
		return x.ActualSizeGb
	}
	return 0
}

type Ec2Network struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Ec2Network) Reset() {
	*x = Ec2Network{}
	if protoimpl.UnsafeEnabled {
		mi := &file_awsec2_model_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ec2Network) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ec2Network) ProtoMessage() {}

func (x *Ec2Network) ProtoReflect() protoreflect.Message {
	mi := &file_awsec2_model_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ec2Network.ProtoReflect.Descriptor instead.
func (*Ec2Network) Descriptor() ([]byte, []int) {
	return file_awsec2_model_proto_rawDescGZIP(), []int{2}
}

var File_awsec2_model_proto protoreflect.FileDescriptor

var file_awsec2_model_proto_rawDesc = []byte{
	0x0a, 0x12, 0x61, 0x77, 0x73, 0x65, 0x63, 0x32, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x94, 0x02, 0x0a, 0x05,
	0x45, 0x63, 0x32, 0x56, 0x4d, 0x12, 0x23, 0x0a, 0x0d, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x69, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x67, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69,
	0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x7a, 0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x7a, 0x6f, 0x6e, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x72, 0x6d, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x70, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x5f,
	0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x70, 0x75,
	0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x0e,
	0x6f, 0x66, 0x66, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x5f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x69, 0x6e, 0x67, 0x43, 0x6c,
	0x61, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x63, 0x79, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x65, 0x6e, 0x61, 0x6e, 0x63, 0x79, 0x12, 0x0e, 0x0a,
	0x02, 0x6f, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6f, 0x73, 0x12, 0x23, 0x0a,
	0x0d, 0x6c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x22, 0x50, 0x0a, 0x07, 0x45, 0x63, 0x32, 0x44, 0x69, 0x73, 0x6b, 0x12, 0x1f, 0x0a,
	0x0b, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x24,
	0x0a, 0x0e, 0x61, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x5f, 0x67, 0x62,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x61, 0x63, 0x74, 0x75, 0x61, 0x6c, 0x53, 0x69,
	0x7a, 0x65, 0x47, 0x62, 0x22, 0x0c, 0x0a, 0x0a, 0x45, 0x63, 0x32, 0x4e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x3b, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_awsec2_model_proto_rawDescOnce sync.Once
	file_awsec2_model_proto_rawDescData = file_awsec2_model_proto_rawDesc
)

func file_awsec2_model_proto_rawDescGZIP() []byte {
	file_awsec2_model_proto_rawDescOnce.Do(func() {
		file_awsec2_model_proto_rawDescData = protoimpl.X.CompressGZIP(file_awsec2_model_proto_rawDescData)
	})
	return file_awsec2_model_proto_rawDescData
}

var file_awsec2_model_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_awsec2_model_proto_goTypes = []interface{}{
	(*Ec2VM)(nil),      // 0: model.Ec2VM
	(*Ec2Disk)(nil),    // 1: model.Ec2Disk
	(*Ec2Network)(nil), // 2: model.Ec2Network
}
var file_awsec2_model_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_awsec2_model_proto_init() }
func file_awsec2_model_proto_init() {
	if File_awsec2_model_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_awsec2_model_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ec2VM); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_awsec2_model_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ec2Disk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_awsec2_model_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ec2Network); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_awsec2_model_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_awsec2_model_proto_goTypes,
		DependencyIndexes: file_awsec2_model_proto_depIdxs,
		MessageInfos:      file_awsec2_model_proto_msgTypes,
	}.Build()
	File_awsec2_model_proto = out.File
	file_awsec2_model_proto_rawDesc = nil
	file_awsec2_model_proto_goTypes = nil
	file_awsec2_model_proto_depIdxs = nil
}
